import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

import TopBar from "@/components/TopBar";
import SiteHeader from "@/components/SiteHeader";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }> | { locale: string };
}) {
  // ✅ Next 16: params can be a Promise
  const { locale } = await Promise.resolve(params);

  if (!routing.locales.includes(locale as any)) notFound();

  // ✅ tells next-intl the active locale
  setRequestLocale(locale);

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          {/* ✅ Shared page shell for ALL pages */}
          <div className="min-h-screen bg-slate-100 py-3 sm:py-6">
            {/* IMPORTANT: no overflow-hidden here, otherwise dropdowns get clipped */}
            <div className="mx-auto max-w-5xl rounded-2xl bg-white shadow-md">
              <TopBar />
              <SiteHeader />
              <Navbar />

              {children}

              <Footer />
            </div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
